config/routes.rb
Rails.application.routes.draw do
  resources :hall_details
  resources :user_with_halls
  resources :users

  root 'users#index'  

end

app/models/hall_detail.rb
class HallDetail < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_with_hall.rb
class UserWithHall < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!"
  end
end

app/controllers/hall_details_controller.rb
class HallDetailsController < ApplicationController
  before_action :set_hall_detail, only: [:show, :edit, :update, :destroy]

  # GET /hall_details
  # GET /hall_details.json
  def index
    @hall_details = HallDetail.all
  end

  # GET /hall_details/1
  # GET /hall_details/1.json
  def show
  end

  # GET /hall_details/new
  def new
    @hall_detail = HallDetail.new
  end

  # GET /hall_details/1/edit
  def edit
  end

  # POST /hall_details
  # POST /hall_details.json
  def create
    @hall_detail = HallDetail.new(hall_detail_params)

    respond_to do |format|
      if @hall_detail.save
        format.html { redirect_to @hall_detail, notice: 'Hall detail was successfully created.' }
        format.json { render :show, status: :created, location: @hall_detail }
      else
        format.html { render :new }
        format.json { render json: @hall_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hall_details/1
  # PATCH/PUT /hall_details/1.json
  def update
    respond_to do |format|
      if @hall_detail.update(hall_detail_params)
        format.html { redirect_to @hall_detail, notice: 'Hall detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @hall_detail }
      else
        format.html { render :edit }
        format.json { render json: @hall_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hall_details/1
  # DELETE /hall_details/1.json
  def destroy
    @hall_detail.destroy
    respond_to do |format|
      format.html { redirect_to hall_details_url, notice: 'Hall detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hall_detail
      @hall_detail = HallDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hall_detail_params
      params.require(:hall_detail).permit(:Hall_Name, :Hall_ID, :Hall_Type, :Phone_Number, :Contact_Email, :Address, :City, :State)
    end
end

app/controllers/user_with_halls_controller.rb
class UserWithHallsController < ApplicationController
  before_action :set_user_with_hall, only: [:show, :edit, :update, :destroy]

  # GET /user_with_halls
  # GET /user_with_halls.json
  def index
    @user_with_halls = UserWithHall.all
  end

  # GET /user_with_halls/1
  # GET /user_with_halls/1.json
  def show
  end

  # GET /user_with_halls/new
  def new
    @user_with_hall = UserWithHall.new
  end

  # GET /user_with_halls/1/edit
  def edit
  end

  # POST /user_with_halls
  # POST /user_with_halls.json
  def create
    @user_with_hall = UserWithHall.new(user_with_hall_params)

    respond_to do |format|
      if @user_with_hall.save
        format.html { redirect_to @user_with_hall, notice: 'User with hall was successfully created.' }
        format.json { render :show, status: :created, location: @user_with_hall }
      else
        format.html { render :new }
        format.json { render json: @user_with_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_with_halls/1
  # PATCH/PUT /user_with_halls/1.json
  def update
    respond_to do |format|
      if @user_with_hall.update(user_with_hall_params)
        format.html { redirect_to @user_with_hall, notice: 'User with hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_with_hall }
      else
        format.html { render :edit }
        format.json { render json: @user_with_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_with_halls/1
  # DELETE /user_with_halls/1.json
  def destroy
    @user_with_hall.destroy
    respond_to do |format|
      format.html { redirect_to user_with_halls_url, notice: 'User with hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_with_hall
      @user_with_hall = UserWithHall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_with_hall_params
      params.require(:user_with_hall).permit(:email, :Hall_ID)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
        if User.exists?(:email => @user.email)
          format.html { redirect_to @user, notice: 'User exists.' }
        else
          @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hall_details_helper.rb
module HallDetailsHelper
end

app/helpers/user_with_halls_helper.rb
module UserWithHallsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hall_details/_form.html.erb
<%= form_for(@hall_detail) do |f| %>
  <% if @hall_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hall_detail.errors.count, "error") %> prohibited this hall_detail from being saved:</h2>

      <ul>
      <% @hall_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Hall_Name %><br>
    <%= f.text_field :Hall_Name %>
  </div>
  <div class="field">
    <%= f.label :Hall_ID %><br>
    <%= f.text_field :Hall_ID %>
  </div>
  <div class="field">
    <%= f.label :Hall_Type %><br>
    <%= f.text_field :Hall_Type %>
  </div>
  <div class="field">
    <%= f.label :Phone_Number %><br>
    <%= f.text_field :Phone_Number %>
  </div>
  <div class="field">
    <%= f.label :Contact_Email %><br>
    <%= f.text_field :Contact_Email %>
  </div>
  <div class="field">
    <%= f.label :Address %><br>
    <%= f.text_field :Address %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :State %><br>
    <%= f.text_field :State %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hall_details/edit.html.erb
<h1>Editing Hall Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @hall_detail %> |
<%= link_to 'Back', hall_details_path %>

app/views/hall_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hall Details</h1>

<table>
  <thead>
    <tr>
      <th>Hall name</th>
      <th>Hall id</th>
      <th>Hall type</th>
      <th>Phone number</th>
      <th>Contact email</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hall_details.each do |hall_detail| %>
      <tr>
        <td><%= hall_detail.Hall_Name %></td>
        <td><%= hall_detail.Hall_ID %></td>
        <td><%= hall_detail.Hall_Type %></td>
        <td><%= hall_detail.Phone_Number %></td>
        <td><%= hall_detail.Contact_Email %></td>
        <td><%= hall_detail.Address %></td>
        <td><%= hall_detail.City %></td>
        <td><%= hall_detail.State %></td>
        <td><%= link_to 'Show', hall_detail %></td>
        <td><%= link_to 'Edit', edit_hall_detail_path(hall_detail) %></td>
        <td><%= link_to 'Destroy', hall_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hall detail', new_hall_detail_path %>

app/views/hall_details/new.html.erb
<h1>New Hall Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', hall_details_path %>

app/views/hall_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hall name:</strong>
  <%= @hall_detail.Hall_Name %>
</p>

<p>
  <strong>Hall id:</strong>
  <%= @hall_detail.Hall_ID %>
</p>

<p>
  <strong>Hall type:</strong>
  <%= @hall_detail.Hall_Type %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @hall_detail.Phone_Number %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @hall_detail.Contact_Email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hall_detail.Address %>
</p>

<p>
  <strong>City:</strong>
  <%= @hall_detail.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @hall_detail.State %>
</p>

<%= link_to 'Edit', edit_hall_detail_path(@hall_detail) %> |
<%= link_to 'Back', hall_details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearningRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_with_halls/_form.html.erb
<%= form_for(@user_with_hall) do |f| %>
  <% if @user_with_hall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_with_hall.errors.count, "error") %> prohibited this user_with_hall from being saved:</h2>

      <ul>
      <% @user_with_hall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Hall_ID %><br>
    <%= f.number_field :Hall_ID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_with_halls/edit.html.erb
<h1>Editing User With Hall</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_with_hall %> |
<%= link_to 'Back', user_with_halls_path %>

app/views/user_with_halls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User With Halls</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Hall id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_with_halls.each do |user_with_hall| %>
      <tr>
        <td><%= user_with_hall.email %></td>
        <td><%= user_with_hall.Hall_ID %></td>
        <td><%= link_to 'Show', user_with_hall %></td>
        <td><%= link_to 'Edit', edit_user_with_hall_path(user_with_hall) %></td>
        <td><%= link_to 'Destroy', user_with_hall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User with hall', new_user_with_hall_path %>

app/views/user_with_halls/new.html.erb
<h1>New User With Hall</h1>

<%= render 'form' %>

<%= link_to 'Back', user_with_halls_path %>

app/views/user_with_halls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user_with_hall.email %>
</p>

<p>
  <strong>Hall id:</strong>
  <%= @user_with_hall.Hall_ID %>
</p>

<%= link_to 'Edit', edit_user_with_hall_path(@user_with_hall) %> |
<%= link_to 'Back', user_with_halls_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>